- name: App Playbook
  hosts: app
  become: true
  tasks:
    - name: Copy Dockerfile
      copy:
          src: "./Dockerfile"
          dest: "~/django/locallibrary//Dockerfile"
    - name: Build Docker 
      docker_image:
        build:
          path: "~/django/locallibrary/"
        name: "djangoapp"
        source: build
    - name: Apply migrations
      docker_container:
        name: "app"
        image: "djangoapp"
        command: python manage.py makemigrations 
        volumes:
          - "~/django/locallibrary/:/usr/src/app"
        detach: false

    - name: Apply database migrations
      docker_container:
        name: "app"
        image: "djangoapp"
        command: python manage.py migrate 
        volumes:
          - "~/django/locallibrary/:/usr/src/app"
        detach: false

    - name: Collect static files 
      docker _container:
        name: "app"
        image: "djangoapp"
        command: python manage.py collectstatic --noinput 
        volumes:
          - "~/django/locallibrary/:/usr/src/app"
        detach: false

    - name: Run test suite 
      docker_container:
        name: "app"
        image: "djangoapp"
        command: python manage.py test 
        volumes:
          - "~/django/locallibrary/:/usr/src/app"
        detach: false

    - name: Create Django superuser 
      docker_container:
        name: "app"
        image: "djangoapp"
        command: "python manage-py createsuperuser --noinput --username=admin --email=admin@{{ inventory_hostname }}.com"
        volumes:
          - "~/django/locallibrary/:/usr/src/app"
        detach: false
      ignore_errors: true

    - name: Run Docker container 
      docker_container:
        name: "app"
        image: "djangoapp"
        state: started
        recreate: true 
        published_ports:
          - "8000:8000"
        volumes:
          - "~/django/locallibrary/:/usr/src/app"
        command: python manage.py runserver 0.0.0.0:8000