- name: Docker Playbook
  hosts: app
  become: true
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
    - name: Clone django repo
      git:
        repo: 'https://github.com/mdn/django-locallibrary-tutorial'
        dest: "~/django/locallibrary"
        force: true
